# Generated by Django 2.1.9 on 2019-06-05 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
